### ISSUE TITLE
Very slow on updated Mac with Yosemite

### ISSUE THREAD

**Issue by acidjunk** [zdia/gorilla#138]
I updated my iMac from OS X 10.8 to 10.10; After that Password Gorilla works but it's very very slow.
I have to resize the screen to trigger a redraw on almost every action. The weird thing is that on other macs I updated from 10.9 -> there is no problem at all.

I already tried reinstalling the app but the problem persists.
Is there a way to start clean?

**Comment by rich123** [comment]
What do you have installed?  The Mac "package" or the Tcl source?

If it is the package, then I would presume MacOS has some form of "uninstall/remove this" somewhere.  Note, I don't have a Mac, so I am not certain of my answer above.

If it is the source, then starting clean should involve nothing more than deleting the folder that contains all of the Password Gorilla files.

If you do have the package installed, can you try downloading a copy of the source and running it to see if the problem continues to occur.  If the source runs fine, then that implies a bug in the ActiveState kit executables.  If the source is just as slow, then that implies something that Apple broke in 10.10, or something that broke for your specific upgrade of your specific machine.

You can get a copy of the current "release" source from here: https://github.com/zdia/gorilla/tree/master
If you would like to try out the newest features, you can grab that from here instead: https://github.com/zdia/gorilla/tree/pre160.

From either page, if you scroll down, near the bottom right will be a button labeled "download zip".  That will allow you to download a zip file of the source.  Then just unpack it into a folder on your Mac, and run the "gorilla.tcl" file inside (should work by just double clicking or using the context menu to pick "run" [or whatever the Mac equivalent label happens to be]).

**Comment by acidjunk** [comment]
thanks for your answer; I'm using the mac package. I finally resolved the problem.
To uninstall I moved Password Gorilla to the trash and I deleted ˜/Library/Preferences/gorilla.rc

Then I installed it again; now all is fine :)

**Comment by gibbisons** [comment]
I am having this same issue  :(  

Today I have downloaded and installed Gorilla 1.5.3.7.1 to my new MacBook Air running Yosimte MacOS.  I do not have any reference to Password Gorilla in my /Library/Preferences folder so cannot follow acidjunk's solution. 

It seems like the click action is not recognised until the window is redrawn OR I click away from the Gorilla app.

**Comment by rich123** [comment]
There was a new MacOS interface layer introduced in the newly released in Tcl/Tk version 8.5.18 (and 8.6.4) (see http://www.codebykevin.com/blosxom.cgi/2015/01/30 for details).  This new MacOS layer might overcome this incompatibility that Apple introduced in the newer OSX version.  

Unfortunately, the new release was just a week ago, and tclkit packages for MacOS tend to lag the releases by several weeks before they become available.  So at the moment I am still waiting for a 8.5.18 version to appear in order to test to see if the new interface layer fixes this issue.
