### ISSUE TITLE
gorilla broken with tclkit 8.6.4??

### ISSUE THREAD

**Issue by CJ-at-github** [zdia/gorilla#140]
I run gorilla in xfce on Arch Linux. Both gorilla and tclkit are installed with aurget from the Archlinux User Repository. I just posted the following problem on aur.archlinux.org/packages/gorilla, but wanted to reach as many potentially helpful folks as possible.
==========
I installed tclkit 8.6.4-1 from the AUR today and now gorilla 1.4-1 refuses to start. Error message is:
    This application requires Tk, which does not seem to be available:
    can't find package Tk
As far as I know, the tcl upgrade is the only potentially impactful change I have made since last running gorilla earlier today.
HELP!! I depend on gorilla. Thanks.

**Comment by rich123** [comment]
Gorilla version 1.4-1 is ancient.  As in we are up to version 1.5.3.7 now ancient.

You would be well suited to download a newer Gorilla version from http://gorilla.dp100.com/downloads/ where you can get standalone Linux packages if you wish to go that route.

But, as you are running Linux, all you need is to have Tcl/Tk installed, download a copy of the source from Github, and run the gorilla.tcl file inside.  If you have Tcl/Tk 8.6 you do need to make one edit to the gorilla.tcl file to change a line that says "package require Tk 8.5" to "package require Tk 8.6".  You may also need to change "tclsh8.5" to "tclsh8.6" on the third line as well.

**Comment by CJ-at-github** [comment]
Excellent direction, and thank you. I'll look to it.
Would be good if you could communicate same to the AUR environment.

**Comment by CJ-at-github** [comment]
Forget my closing comment about communicating to the AUR envirment. I now see that the package has been renamed and version 1.5.3.7-1 is available at https://aur.archlinux.org/packages/password-gorilla/.

**Comment by rich123** [comment]
Ah, glad to know the newer version is already in the Arch repository.
