### ISSUE TITLE
Password Gorilla cannot be opened

### ISSUE THREAD

**Issue by PeterSliepenbeek** [zdia/gorilla#146]
Password Gorilla generates the following log:
grab failed: another application has grab
grab failed: another application has grab
    while executing
"grab $top"
    (procedure "LockDatabase" line 111)
    invoked from within
"LockDatabase"
    (procedure "::gorilla::IdleTimeout" line 2)
    invoked from within
"::gorilla::IdleTimeout"
    ("after" script)

**Comment by rich123** [comment]
Can you provide some more info.  

1) operating system
2) desktop environment (if linux for #1)
3) are you running the packaged .exe or from the source files?
4) which version of gorilla
5) is, by chance, a second copy of gorilla already running?

**Comment by PeterSliepenbeek** [comment]
1) Gentoo (Linux)
2) KDE
3) from source files
4) 1.42
5) no

**Comment by rich123** [comment]
Version 1.42 is quite ancient.  The current version is version 1.5.3.7.  Please download the 1.5.3.7 source files from github (you can find them here: https://github.com/zdia/gorilla/releases/tag/v1.5.3.7) and test to see if the newer version exhibits the same issue.

**Comment by PeterSliepenbeek** [comment]
My fault, the latest version appears not to suffer from the reported behaviour. In my opinion this ticket can be closed.
