### ISSUE TITLE
Strange error messages in 1.5.3.7 on Debian Sid AMD64

### ISSUE THREAD

**Issue by mithrades** [zdia/gorilla#149]
when opening an existing data base and adding a new login when executing OK I receive the following:

couldn't execute "ifconfig": no such file or directory
couldn't execute "ifconfig": no such file or directory
    while executing
"exec ifconfig"
    (procedure "dump" line 2)
    invoked from within
"dump"
    (procedure "::nettool::mac_list" line 3)
    invoked from within
"::nettool::mac_list"
    (procedure "::nettool::hwid_list" line 3)
    invoked from within
"::nettool::hwid_list"
    (procedure "generate_tcl_machinfo" line 36)
    invoked from within
"generate_tcl_machinfo"
    (procedure "generate_tcl" line 7)
    invoked from within
"generate_tcl"
    (procedure "generate" line 6)
    invoked from within
"generate"
    (procedure "uuid::uuid" line 7)
    invoked from within
"uuid::uuid generate"
    (procedure "PopulateRecord" line 20)
    invoked from within
"PopulateRecord [ set newrn [ $::gorilla::db createRecord ] ] "
    (procedure "Ok" line 30)
    invoked from within
"Ok"
    (in namespace inscope "::gorilla::LoginDialog::0" script line 1)
    invoked from within
"namespace inscope ::gorilla::LoginDialog::0 Ok"
    invoked from within
".nmLoginDialog0.bf.top.ok invoke "
    invoked from within
".nmLoginDialog0.bf.top.ok instate !disabled { .nmLoginDialog0.bf.top.ok invoke } "
    invoked from within
".nmLoginDialog0.bf.top.ok instate pressed { .nmLoginDialog0.bf.top.ok state !pressed; .nmLoginDialog0.bf.top.ok instate !disabled { .nmLoginDialog0.bf..."
    (command bound to event)

clicking on OK to remove the error message I then click on save to save the new login and receive another error message:

Failed to save password database as (location of data base.dat): record 262 does not exist

by clicking on OK for that message and exiting password gorilla I get the 'current password database has been modified: etc as ask me if I want to save the database by clicking on YES if I do that the new entry is not saved 

If I click on NO the database which is supposed to be saved immediately anything is changed  anyway,  the data base with the new entry has always (in the past) saved the updated information so I was able to save the information (already saved) by clicking on NO button and the program then exits. This runs counter to intuition of course, but if I clicked on YES to save the database I then get the error message about record 262 not existing..so by clicking on the NO button (to not save the changed data base that has already been saved) the program then closes.

In the past I used password gorilla like this for a long time but now it is refusing to save my new entry even after 'saving' as soon as a new entry is entered and selecting the NO button in the closing and saving dialog and now does not save the new entry on closing.

This is a big problem if I cannot rely on it to save a new entry. I have used PG a long time and like the program and have had no problems I couldn't work around until now. Need a fix here.

Thanks

**Comment by rich123** [comment]
There is already a fix available.  The cause is you appear to have upgraded (or something else upgraded you) to Tcllib 1.17, which is buggy with regards to its UUID generation module.

This bug is the reason for commit 6284d86ebafc8a65ad7e1fc1626282317d608788 on the pre160 branch.  The fix is to skip using Tcllib's now buggy implementation and instead generate Type 5 UUID's within gorilla directly.

You can grab the code that is the pre160 branch from here https://github.com/zdia/gorilla/tree/pre160 (use the "Download Zip" button), but if you installed via the official Debian repository then this does not give you a Debian package file.

**Comment by mithrades** [comment]
Thank you for the link above for version 1.5.3.8 however I'm stuck on what to do after opening the gorilla.tcl file as it would not open my database complaining about a lot of things:

can not open database "errorcode NONE -errorinfo (unknown preference type:
while executing

"error [mc "unknown preference type: %s $prefType]"
etc.

how does one set these preferences it is asking for?

**Comment by rich123** [comment]
Hmm...  Ok, I just tried download what github delivers as pre160, and I get something similar on my dev system.  I'm not sure what's up just yet, but clearly somethings up with the pre160 branch on github.

Now to do more digging.

**Comment by rich123** [comment]
I just pushed a new commit onto pre160.  It fixes the issue for me on my 64-bit system that exhibited the same issue you saw when I tried the github code.  The pre160 branch still had a stale twofish.so file in it for x86_64.  This push replaces the stale twofish.so with the fixed twofish.so, and fixes the issue on my 64-bit system.  So I am betting it will fix the issue on yours as well.

**Comment by mithrades** [comment]
Thank you for your good work, the non starting issue has been fixed. 

There's just one more thing  ;-)

If I have selected in (Preferences) the "Auto-save database immediately when changed" (box) why do I need to see the warning message when closing PG telling me the database has been modified and asking if I want to save it. Now here's the odd thing, if I click on the YES button it runs the saving progress bar again but does not shut down. If I again go to file and exit or Ctrl-X the warning box is brought up again in a 'loop.' If I then hit the NO box meaning I do not want to save the changes to the database then PG exits normally whilst still saving the changes. It took me some anxious moments to figure this out thinking I was saving then dumping my changes to close the program.

I'm suggesting if the box to save immediately in preferences is checked, the database warning box on closing PG should not have to come up. Only if that box in preferences isn't checked would the warning be required for a yes or no to save the changes, at the close of PG.

Since I can see the saving bar graph saving each change as it occurs, I feel confident on closing PG with no other reminders.

**Comment by rich123** [comment]
Glad the updated .so file fixed the issue.

On your other item, that seems like the auto-save is not marking the file state as "saved" when it fires and completes saving.  I've created issue #150 on your behalf to track that item for the moment.

**Comment by mithrades** [comment]
Thank you, good show.
