### ISSUE TITLE
"keepBackupFile=0"/"Backup database on save" Option Does Not Work

### ISSUE THREAD

**Issue by AntumDeluge** [zdia/gorilla#156]
Not sure if this issue has been fixed in development.

If "Backup database on save" option is unchecked ("keepBackupFile=0") a backup is still created.

**My System**
Password Gorilla version: 1.5.3.7
OS: Linux Mint 18 (Sarah) x86_64
Linux Kernel: 4.4.0-31-generic
![Screenshot](https://cloud.githubusercontent.com/assets/3631473/17080597/607320f2-50ea-11e6-8490-1b6ad0c21036.jpg)

**Comment by rich123** [comment]
What is set for the "Time stamp backup" option on the "Defaults" tab?  @zdia added that option some time ago and it also functions as a 'save a backup copy' option, except that instead of only having one ".backup" file, you have one file per save-point with date and time encoded into the file-name.

**Comment by AntumDeluge** [comment]
![Defaults Tab](https://cloud.githubusercontent.com/assets/3631473/17080761/cbbc19ee-50f0-11e6-93de-de7b05583bf5.jpg)

**Comment by AntumDeluge** [comment]
Security->Customize does not have a corresponding "Time stamp backup" option. Is that how it should be?
![Security->Customize Dialog](https://cloud.githubusercontent.com/assets/3631473/17080771/1dca0a7a-50f1-11e6-9255-57403cf85bff.jpg)

**Comment by rich123** [comment]
You've located an honest issue that got overlooked somewhere.  On my dev copy I also get a *.bak file created, even when the "backup database on save" option is off.

**Comment by rich123** [comment]
Re: your "customize" question - yes, the settings there are part of the PasswordSafe file format itself while the options in the "preferences" dialog are specific to Gorilla.

**Comment by rich123** [comment]
Further Re: your "customize question" - the text at the bottom of the defaults tab in preferences is confusing - it applies to everything _except_ the time-stamp backup option.  That's a third change to make...

**Comment by AntumDeluge** [comment]
Thanks very much for looking into this issue.

**Comment by rich123** [comment]
Issue fixed - confusing layout of "timestamp backup" corrected - help.txt modified to match changes - closing issue.
