### ISSUE TITLE
Featuer Request: "View Login" Option for Double-click

### ISSUE THREAD

**Issue by AntumDeluge** [zdia/gorilla#157]
I'd like to have the option to open the "view" dialog for double-clicking a login.
![View Login Double-click option mockup](https://cloud.githubusercontent.com/assets/3631473/17080750/4bd40750-50f0-11e6-8ba1-dd527030d1be.jpg)

**Comment by rich123** [comment]
Good suggestion.  Thanks for the additional idea.

**Comment by rich123** [comment]
Suggestion added - closing issue now.
