### ISSUE TITLE
Ubuntu 16.04 Linux - icon in Unity doesn't match

### ISSUE THREAD

**Issue by dlehammer** [zdia/gorilla#161]
Installing Password Gorilla from Ubuntu Software includes a nice icon.
But upon launching Gorilla the icon "link" is broken and Unity uses generic icons in the sidebar and alt+tab menu. Using up 2 icons in the sidebar when Gorilla is running.

Example 1: open database symptom (ie. a Gorilla icon is present + a generic icon)
![ubuntu_16 04_symptom_open_database](https://cloud.githubusercontent.com/assets/17439718/20405701/96ef3f86-ad0a-11e6-8d1d-fac6513c4d20.png)

Example 2: locked database symptom (ie. a Gorilla icon is present + a generic icon)
![ubuntu_16 04_symptom_locked_database](https://cloud.githubusercontent.com/assets/17439718/20405740/bea00d58-ad0a-11e6-836e-1c106e31a0b0.png)

I've used Gorilla for many years, in Ubuntu, and this issue has always bothered me - especially when I had multiple different applications open where the icon "link" was broken.

But I've stumbled over a [fix](http://askubuntu.com/a/558441/599669) that seems to restore the "link" (window matching) for both sidebar and alt+tab switch:

`$ sudo nano /usr/share/applications/password-gorilla.desktop`

append the following to the file, save and exit - result is visible immediately.

`StartupWMClass=Gorilla`

Result:
![ubuntu_16 04_w_startupwmclass gorilla](https://cloud.githubusercontent.com/assets/17439718/20405898/7548e96c-ad0b-11e6-9939-8d414036a8bc.png)

I'll attempt to create a pull-request, when this issue has been created.

Best regards,

DH 

Edit: added link to fix in-order to provide credit to original approach for fix.

**Comment by rich123** [comment]
Fixed by merging pull request from @dlehammer.  Closing the issue now.
