### ISSUE TITLE
Bug when choose to export as .txt

### ISSUE THREAD

**Issue by kodekrendel** [zdia/gorilla#166]
Even if I choose export database as .txt it exports as .csv. 
Ubuntu 16.04.

**Comment by rich123** [comment]
Given that a .csv file is also a text file (change the extension to .txt, it will open as a text file), what were you expecting to receive for a "text" export?

**Comment by kodekrendel** [comment]
@rich123 maybe a file with .txt extension? Then why to provide this option if export to .csv anyway? Logic?

**Comment by rich123** [comment]
That portion of the code long pre-dates my joining PWGorilla, so I can't comment on the logic of why for that portion.  Having looked at it now, the selection of "text" on the file selection dialog simply chooses what files are displayed to select from by use of the mouse, but it does not actually effect the file extension (unless a user explicitly provides an extension, in which case the provided extension is used as-is).  Given that the contents is always a csv irrespective of the extension, unless there is a specific textual but non-csv format that might be useful, one possibility for change would be to just drop the "txt" option for the selector and have only csv and "all files" options available.

**Comment by kodekrendel** [comment]
Yes, then it won't be so confusing.
