### ISSUE TITLE
pre160: delete password from history doesn't work

### ISSUE THREAD

**Issue by ajraymond** [zdia/gorilla#178]
Hi Zbigniew,

While testing the pre160 branch, I noticed that the 'delete' action in the password history does nothing.

There doesn't seem to be anything hooked to this button:
`ttk::button $f.hdel   -text [ mc Delete ] -state disabled ]`

I thought I'd raise a bug so it isn't forgotten.

Regards,
Alexandre

**Comment by rich123** [comment]
Indeed.  Good catch.  I think I might get a chance to fix that this weekend.  Also, thanks for the updated translations.  I'll take a closer look (and try to merge them) soon as well.

**Comment by rich123** [comment]
Updates merged.  Many thanks for the updates.
