### ISSUE TITLE
Can not open password database "":can't read "subKeys": no such variable

### ISSUE THREAD

**Issue by s256** [zdia/gorilla#181]
Hi all,

actually I'm not sure if it's a gorilla or environment issue:

I'm accessing my same old database. Via Windows (10) and Linux (Fedora 27). Windows is using the latest release (1537_x64). On Fedora I was using the latest git version. After the error `Can not open password database "":can't read "subKeys": no such variable` appeared I tried the latest release - same error. I'm pretty sure the DB-File is ok, as it is working under windows.

Fedora 27 details:
tcl.x86_64                             1:8.6.7-1.fc27
tcllib.noarch                          1.18-2.fc27
tk.x86_64                              1:8.6.7-1.fc27

I'm just facing this issue with my oldest password database. Another one, not as old, but still old. is working fine.

Any clues?

Best
Sebastian

**Comment by rich123** [comment]
Right now, I'm unsure of the cause as well, although there seems something is not quite right somewhere.  One question, when you say "latest git version" do you mean the current tip of the pre160 branch?  If not, could you also try with the tip of the pre160 branch?

Second, when this error pops up, there should be a button labeled "details" on the dialog box.  If you push it you will get a more detailed report.  Can you copy in the contents of that more detailed report here?

**Comment by s256** [comment]
I'm referring to the master branch. I just tried the pre160 branch (executing the gorilla.tcl in sources/ ). Same error. Unfortunately there is no "details" button. (Screenshot attached)
![gorilla](https://user-images.githubusercontent.com/1517486/35739066-c660e0e4-0830-11e8-87a8-4ceb5459c9f1.jpg)

**Comment by rich123** [comment]
That screen shot is of the "wrong password" dialog.  The "details" button would appear on the dialog that has this quote from the first entry here: "Can not open password database "":can't read "subKeys": no such variable".

**Comment by s256** [comment]
F***.  But still there is no "Details" button... prove:
![gorilla](https://user-images.githubusercontent.com/1517486/35769940-56a17a28-0913-11e8-8c59-f8eb6252cf15.jpg)

**Comment by rich123** [comment]
Ok, so we will need to do a little digging to see what is up.

I understand this is popping up on Linux, and I also believe you are running the source from github, right?

If so, edit the file pwsafe.tcl in the sources/pwsafe directory, find the line that begins: "proc pwsafe::createFromFile", and then scan down about 25 lines until you see a line reading "if {[catch {".  About 6 lines farther will be a line reading "} result oops]} {".  On the very next line, insert this above the "itcl::delete" line:
puts stderr "result\n$result\noops\n$oops"

Then, run gorilla from a terminal (xterm, rxvt, etc.) so you can see the output from the puts in the terminal, and try to open the same database that fails.  More detail info should spit out into the terminal when you get the error message.  Copy/paste the extra details from the terminal here.

**Comment by s256** [comment]
here we go:
[se@se-u747 sources]$ ./gorilla.tcl 

oops                                                                    ºE
-errorstack {INNER loadScalaºE CALL {::pwsafe::db::ecb1 decryptBlock íÜº  èÌ ®g£J} CALL {my decryptField íÜº  èÌ ®g£J>
                                      2aéQ¢ëêÍ} CALL {::pwsafe::db1 getPassword} CALL {::pwsafe::reader1 readFile pcv} CALL {pwsafe::createFromStream ::pwsafe::streamreader1 Dw2014nFW! 2 pcv} CALL {pwsafe::createFromFile /home/se/whu.dat Dw2014nFW! junk}} -errorcode {TCL READ VARNAME} -errorinfo {can't read "this": no such variable
    while executing
"twofish_c decrypt $this $block"
    (object "::pwsafe::db::ecb1" method "::itwofish::ecb::decryptBlock" body line 1)
    invoked from within
"$engine decryptBlock  [string range $encryptedMsg [expr {16*$i}] [expr {16*$i+15}]]"
    (object "::pwsafe::db1" method "::pwsafe::db::decryptField" body line 6)
    invoked from within
"decryptField $password"
    (object "::pwsafe::db1" method "::pwsafe::db::getPassword" body line 2)
    invoked from within
"$db getPassword"
    (object "::pwsafe::reader1" method "::pwsafe::v2::reader::readFile" body line 60)
    invoked from within
"$reader readFile $pcvp"
    (procedure "pwsafe::createFromStream" line 17)
    invoked from within
"pwsafe::createFromStream $stream $password 2 $pcvp"} -errorline 30 -code 1 -level 0

**Comment by rich123** [comment]
At first glance, something there gives me a gut feeling that there is a bit of data corruption in the file somewhere.

You say the same file loads in Windows but not Linux, right?  If yes, try this:

1) load the file in Windows
2) save the file under a different name from Windows
3) try loading the newly saved file in Linux

Do you still get the error after that cycle?

I'll also dig deeper into what that trace above says, but I likely won't have any real time for that until this weekend.

**Comment by s256** [comment]
Yeah I was thinking of data corruption too, but I wasn't sure if the windows application should behave as the linux one does.

I tried the three steps: same error.  

No worries, take all the time you need. Thanks for your work!

**Comment by rich123** [comment]
Ok, an additional test.  Which architecture is your linux machine, 32 bit or 64 bit?

Look in your gorilla/sources/twofish directory.  Inside you'll find a linux-ix86/ and a linux-x86_64/.  The ix86 directory is for 32-bit, the x86_64 is for 64-bit.  Move the directory for your machine somewhere else temporally (/tmp is an ok choice, and if you are not sure of 32 vs 64 bit, just move both out).
Then try launching a new gorilla instance and try opening the safe that fails.
Does it work, or does it go south still?

**Comment by rich123** [comment]
Opening a working file should show this in "Help->About" after the file is open:

![after](https://user-images.githubusercontent.com/305956/36066201-f87d6824-0e73-11e8-8b42-630101a3a4a0.png)

The same window, before making the change, should look like this:

![before](https://user-images.githubusercontent.com/305956/36066204-087f8b26-0e74-11e8-8682-7ff9ba81ccdb.png)

**Comment by s256** [comment]
Hi,  architecture is x64. I moved the lib. The extension was not loaded(like in your screenshots). But still the same behaviour and same error message.  

`result

oops
-errorstack {INNER loadScalar1 CALL {my intDecrypt 1542534602 3787859225 1427273736 3584301188} CALL {::pwsafe::db::ecb0 decryptBlock {Ê5ñ[%ÆxU
                                                                                                                                                 ¤Õ}} CALL {my decryptField {Ê5ñ[%ÆxU
                                                                                                                                                                                        ¤Õ"M`\+"pd
                                                                                                                                                                                                     æ.c}} CALL {::pwsafe::db0 getPassword} CALL {::pwsafe::reader0 readFile pcv} CALL {pwsafe::createFromStream ::pwsafe::streamreader0 123456 2 pcv} CALL {pwsafe::createFromFile /home/se/test.dat 123456 junk}} -errorcode {TCL READ VARNAME} -errorinfo {can't read "subKeys": no such variable
    while executing
"lindex $subKeys 4"
    (object "::pwsafe::db::ecb0" method "::itwofish::itwofish::intDecrypt" body line 6)
    invoked from within
"intDecrypt $x0 $x1 $x2 $x3"
    (object "::pwsafe::db::ecb0" method "::itwofish::ecb::decryptBlock" body line 9)
    invoked from within
"$engine decryptBlock  [string range $encryptedMsg [expr {16*$i}] [expr {16*$i+15}]]"
    (object "::pwsafe::db0" method "::pwsafe::db::decryptField" body line 6)
    invoked from within
"decryptField $password"
    (object "::pwsafe::db0" method "::pwsafe::db::getPassword" body line 2)
    invoked from within
"$db getPassword"
    (object "::pwsafe::reader0" method "::pwsafe::v2::reader::readFile" body line 60)
    invoked from within
"$reader readFile $pcvp"
    (procedure "pwsafe::createFromStream" line 17)
    invoked from within
"pwsafe::createFromStream $stream $password 2 $pcvp"} -errorline 30 -code 1 -level 0
`

**Comment by rich123** [comment]
Ok, from that trace I see that this particular file is formatted in the version 2 format.

At the moment I don't see why that should matter, but there are some newer features of the V3 format that are not available with V2, so you might consider opening it on windows (where it works for some unknown reason) and toggling the Security -> Customize -> Use Password Safe 3 format option, then saving a new copy out under windows.

That new, V3 format file, should then open on Linux without incident (hopefully).

I tried creating an empty V2 format file myself, and it opens without incident for me, so at the moment I'm at a loss to explain why this one is failing for you in the way it is failing.

**Comment by s256** [comment]
Yep. That solved the problem for me. Feel free to close the issue. Thanks for your help!

**Comment by rich123** [comment]
Good to know that did fix it.  I've still been unable to recreate the issue here.  I even installed 8.6.7 to see if it might have been something in that version, but no it worked here.

I'll close out the issue now.
