### ISSUE TITLE
Feature request: Close "Find" and "Add/Edit/View" windows on Escape key

### ISSUE THREAD

**Issue by Keith-S-Thompson** [zdia/gorilla#184]
Typing the Escape key should close the current window.

This should probably apply to all windows other than the top-level one, but the "Find" window is the one where I'd really like to have this feature.

**Comment by rich123** [comment]
Binding Escape to close the find window is a good idea.  Good enough that it was the topic of issue #153 and was added in commit 99ea8a534c59351e168bd59fc800815d9cf6fb74 which is now in the ancestry of the current pre160 branch.

The other windows don't have Escape mapped as a "close this" action.  Preferably it would be a "close, but only if no unsaved changes exist" action.

**Comment by rich123** [comment]
Commit 23ae3e1d91a29accc348c031c5c80d6e99e1afea should take care of the remaining dialog windows.
