### ISSUE TITLE
Windows 10 update has broken TCL

### ISSUE THREAD

**Issue by timp** [zdia/gorilla#186]
I am using gorilla1537_64.exe pre-built and have been for some years on Windows 10 Enterprise version 1703 OS Build 15063.1088 at work. 

A recent upgrade has broken password gorilla which now fails with: 

Password Gorilla was unable to create a debug log file.
Please copy and paste the contents of this window into am email to
PWGorilla@t-online.de
Use Control+c to copy

-begin------------------------------------------------------------------
Statusinfo created Jun 07 2018 15:57:28
Password Gorilla version: $Revision: 1.5.3.7 $
Failure to load package: Itcl
catch result: couldn't load library "C:/timp/bin/gorilla1537_64.exe/lib/itcl3.4/itcl34.dll": this library or a dependent library could not be found in library path
catch options: -code 1 -level 0 -errorcode NONE -errorinfo {couldn't load library "C:/timp/bin/gorilla1537_64.exe/lib/itcl3.4/itcl34.dll": this library or a dependent library could not be found in library path
    while executing
"load C:/timp/bin/gorilla1537_64.exe/lib/itcl3.4/itcl34.dll Itcl"
    ("package ifneeded Itcl 3.4" script)
    invoked from within
"package require Itcl"
    invoked from within
"catch "package require $package" catchResult catchOptions "} -errorline 9
auto_path: C:/timp/bin/gorilla1537_64.exe/lib/app-gorilla C:/timp/bin/gorilla1537_64.exe/lib/app-gorilla/tcllib C:/timp/bin/gorilla1537_64.exe/lib/tcl8.5 C:/timp/bin/gorilla1537_64.exe/lib C:/timp/bin/gorilla1537_64.exe/lib/tk8.5 C:/timp/bin/gorilla1537_64.exe/lib/tk8.5/ttk C:/timp/bin/gorilla1537_64.exe/lib/app-gorilla/itcl3.4
modules path: C:/timp/bin/gorilla1537_64.exe/lib/app-gorilla/modules C:/timp/lib/tcl8/site-tcl C:/timp/lib/tcl8/8.0 C:/timp/lib/tcl8/8.1 C:/timp/lib/tcl8/8.2 C:/timp/lib/tcl8/8.3 C:/timp/lib/tcl8/8.4 C:/timp/lib/tcl8/8.5 C:/timp/bin/gorilla1537_64.exe/lib/tcl8/site-tcl C:/timp/bin/gorilla1537_64.exe/lib/tcl8/8.0 C:/timp/bin/gorilla1537_64.exe/lib/tcl8/8.1 C:/timp/bin/gorilla1537_64.exe/lib/tcl8/8.2 C:/timp/bin/gorilla1537_64.exe/lib/tcl8/8.3 C:/timp/bin/gorilla1537_64.exe/lib/tcl8/8.4 C:/timp/bin/gorilla1537_64.exe/lib/tcl8/8.5
tcl_platform: osVersion 6.2 pointerSize 8 byteOrder littleEndian threaded 1 machine amd64 platform windows os {Windows NT} user pizeyt wordSize 4
info library: C:/timp/bin/gorilla1537_64.exe/lib/tcl8.5

**Comment by rich123** [comment]
Something that changed in W10 has resulted in your pre-built gorilla not being able to load a .dll file it needs to operate.

The interesting part is that I have access to W10 Enterprise N 2016 LTSB version 1607 OS build 14393.2189 on my work machine and the same gorilla executable runs just fine on that version (just tested with a fresh download).  So something in W10 1703 has broken things.  Just what changed to break things I do not know, because with the exception of the locked down work machine I have zero other mswindows machines.  So just now I'm quite at a loss to produce any suggestion on how to fix at this time (beyond suggesting you possibly try installing a windows Tcl and then try running the PWGorilla with an installed windows Tcl, provided you can, and are allowed to, install to the machine).

**Comment by rich123** [comment]
If you can, give this file a try:

GPG signature:
https://gorilla.dp100.com/downloads/gorilla-1.5.3.7-v1.5.3.7-1c17048e09131fa613193c52f498c66a1e7b01c7-win64.exe.sig

W64 EXE file:
https://gorilla.dp100.com/downloads/gorilla-1.5.3.7-v1.5.3.7-1c17048e09131fa613193c52f498c66a1e7b01c7-win64.exe

The exe file should give you a sha256sum value of 8c65d9f2ff965c989640dd9120185d8d185aef117e2529e74f13aba54a1d6009 after you download it.

That is 1.5.3.7, packaged into a new tclkit w64 executable from Roy Keene's kit creator (http://kitcreator.rkeene.org/kitcreator).  It runs on my w10 V 1607 work machine, but that provides little given that the old exe also worked on the V 1607 w10 system.

**Comment by timp** [comment]
That one does work, thank you.

I have also create a simple batch file as per the README:
```
cd C:\\gorilla\sources
gorilla.tcl %1
```

**Comment by rich123** [comment]
Good to know.  That (newer) tclkit is 8.6.8, and for the 8.6 series Itcl is a Tcl wrapper based on TclOO (built in to 8.6) so there is no Itcl*.dll to load.  I was hopeful that this would work around the problem.

I'll update the downloads page to reference this new file.

Downloads page updated.  Closing issue.

**Comment by timp** [comment]
Thanks Rich for fantastic turnaround!

**Comment by mafzala** [comment]
Thanks @rich123 - Its very helpfull -
