### ISSUE TITLE
GPG RSA key expired

### ISSUE THREAD

**Issue by ghapereira** [zdia/gorilla#189]
Hi, trying to verify the GPG signature for the Mac version 15373 today I found out that the signature is good but the key is expired. I got the key from https://github.com/zdia/gorilla/wiki/Verifying-integrity-of-release-files.

**Comment by rich123** [comment]
Issue fixed - non-expired signing key placed on the wiki page.

I actually forgot about this copy of the key when I extended the expiration date.  Thanks for bringing it to my attention.

**Comment by ghapereira** [comment]
Thank you, it is ok now!
