### ISSUE TITLE
Feature Request - please add Auto Save Feature

### ISSUE THREAD

**Issue by surapuramakhil** [zdia/gorilla#205]
Hie, I am unfortunate to say this that I lost **few passwords** just on missing save every time I update or change something.
It would be great if it automatically save things instead of making me clicking or saving every time.

**Comment by ei8fdb** [comment]
![Preferences_and_Password_Gorilla](https://user-images.githubusercontent.com/1899506/61992438-6c2bda00-b056-11e9-922c-88342ab1e512.jpg)

The autosave option is in preferences (at least on OS X).

**Comment by surapuramakhil** [comment]
thank you @ei8fdb .
It's also present in Ububuntu to. Enabled it.

**Comment by rich123** [comment]
Also, please note that the "auto-save" setting is a setting that has a storage location within the actual encrypted password file.  So to change an existing file to "auto-save" you will need to open the encrypted file, and then use the "Security"->"Customize" menu entry to open a dialog where you can toggle on the "auto-save" feature for the existing encrypted file.
