### ISSUE TITLE
Can not open password database: Insufficient data in password history field to scan header

### ISSUE THREAD

**Issue by abjennings** [zdia/gorilla#206]
I installed PWGorilla on PureOS (Debian based).  In the initial dialog box, when I select the file and type in the password, I get the following error:

Can not open password database: Insufficient data in password history field to scan header

This file opens fine on Windows.  Any ideas?

**Comment by rich123** [comment]
> Any ideas?

What version of PWGorilla?

In 1.6.0-beta-2 the message comes from this check in pwsafe/pwsafe-v3.tcl:

```
if { [ string length $fieldValue ] < 5 } {
  error "Insufficient data in password history field to scan header."
}
```

And it means the file parser found a history record, but the record it found was too short (expected length is a minimum of five characters).

> This file opens fine on Windows.

What program/version of that program are you using to open the file on Windows?

> I installed PWGorilla on PureOS (Debian based).

Did you install the Tcl source version?  If so, you could make a temporary edit that would reveal more about what has gone wrong.  Find where the pwsafe/pwsafe-v3.tcl file is stored on your system, then:

1) make a backup copy

2) edit the file and change the lines (these occur on lines 379-381 in 1.6.0-beta2) from:

```
if { [ string length $fieldValue ] < 5 } {
  error "Insufficient data in password history field to scan header."
}
```

to

```
if { [ string length $fieldValue ] < 5 } {
  puts stderr "Short history field found.  length=[string length $fieldValue]"
  puts stderr "Field contents: [binary scan [encoding convertto utf-8 $fieldValue] H* z ; set z]"
  error "Insufficient data in password history field to scan header."
}
```
Then run gorilla from a terminal (i.e., xterm, gnome-terminal, etc.) and watch for output to be printed to the terminal.  Then paste the output messages into a reply here.

**Comment by abjennings** [comment]
Thanks for the quick response!

It was version 1.6.0-beta-1.  I was just using the one installed by the Gnome "Software" installer.

The pwsafe3 file was last written by PWGorilla 1.5.3.7 on Windows and opens fine with that version.

Your instructions got me to clone the repo from GitHub and run it.  It worked.  I think I can work with that.

Thanks again!
