### ISSUE TITLE
how to give permission for gorilla to access documents?

### ISSUE THREAD

**Issue by keutsler123** [zdia/gorilla#211]
I recently updated my iOS and the first time I went to access gorilla it asked for permission to access my documents. I accidentally said no, and now I can't access my database nor find a way to give permission. Any help?

**Comment by rich123** [comment]
Sorry, no, I have no idea, other than to suggest that logically there should be a way, somewhere, to review and edit the given permissions.

But I have no Mac machine, so I have no knowledge of how to do so.  Maybe someone else here who does have a Mac will know?

**Comment by LazaRocks** [comment]
* Open the `System Preferences` app, click on `Security and Privacy` and choose the `Privacy` tab. 
* On the left pane choose `Files and Folders`. On the right pane you should have the title: "Allow the apps below to access files and folders". Navigate to the `Gorilla` app and tick the required permissions.

**Comment by ciampix** [comment]
IMHO this is not a Gorilla issue but a general application - permission - MacOS related issue. I would close it right away...

**Comment by rich123** [comment]
@ciampix - good point.  Closing as not specific to Gorilla.
