### ISSUE TITLE
weird notes font

### ISSUE THREAD

**Issue by Unixware** [zdia/gorilla#217]
Hi,

I am using the gorilla under xfce, the fonts on notes are really weird, each font is like a "block" with a space on the end. I bet is some font missing from my setup (manjaro/arch) . may I ask what is the font that you use for the notes text-field ? thanks

**Comment by Unixware** [comment]
false alarm... a reboot solved that!

**Comment by rich123** [comment]
FWIW, the notes box is a Tk text widget, and it uses the default font that Tk picks to utilize for a text widget.

You can determine which actual font is used on your system by doing the following (presuming you have the Tcl/Tk interpreter installed, most Linux systems at least have it available in their package repos):

```
$ wish
% text .t
.t
% .t cget -font
TkFixedFont
% font actual TkFixedFont
-family {DejaVu Sans Mono} -size -12 -weight normal -slant roman -underline 0 -overstrike 0
```
The above shows what Tk picks on my Slackware system.

**Comment by Unixware** [comment]
many thanks, I really appreciate it.
Probably some of the packages/updates installed the missing fonts , it's a fresh installation and I updated it with packages I needed.
