### ISSUE TITLE
macOS Monterey shows no databases in dropdown

### ISSUE THREAD

**Issue by gbolte** [zdia/gorilla#225]
I set up a database about a while ago, and I accessed it and used the users/passwords in it about a month ago. However, I went to log in to it today, and I don't see any databases in the dropdown. I tried to manually open the database by browsing for it, but I have no idea where the database files are stored.  Can anyone help me?

**Comment by rich123** [comment]
> and I don't see any databases in the dropdown.

That is odd.  I don't know why it would be doing that at this time.

> but I have no idea where the database files are stored.

The default for a new database is wherever MacOS sets as the processes current working directory.  But, you can change the location where a new database is stored as part of saving that DB.  If you simply took the defaults, then you might find "where" by going through the process of creating another new db, adding at least one fake record (so it is marked as "changed") and then beginning the process of saving it.  When the dialog appears where you can pick a different location and/or different filename you may be able to determine in what directory on disk it is defaulting to using.  And if you saved your real file in the same default, your real file should also be visible once you navigate to that location.

Alternately, if you remember the name you used, or if you left the default extension (.psafe3) on the file, then you can use a terminal session to look for that file.  You'd need to open up a terminal (I think it is under "Utilities" in the MacOS desktop UI, but as I do not have a Mac, I can't verify that) and once open, provided MacOS' find work's close enough to its Linux counterpart, this should find all files named *.psafe3 located in or beneath your user's home directory:
```
find ~ -name \*.psafe3 
```
If you remember the name you used, you can also search for that name (assuming you kept the default extension):
```
find ~ -name (name you used here).psafe3
```
I.e., if you named it Passwords.psafe3 you'd enter:
```
find ~ -name Passwords.psafe3
```
to look for the file.  Do note that the above commands may take some time if you have a lot of files, and do not have an SSD/Flash drive.

**Comment by gbolte** [comment]
Hi Rich,

Thanks for the response.  I'm not sure what I did, but I must have not saved my original DB or deleted it.  I created a new test one, and it was saved by default in my documents folder.  There are no other PWG DBs in that folder and searching for /psafe3 files didn't turn anything up.  

It's not a huge deal since I only had a couple passwords saved in it, so I can easily reset them.  I'll try creating it again, and pay more attention to each step.  If I can recreate the issue I ran into, I'll bring it up here.  For now, just consider this a pebkac.

**Comment by rich123** [comment]
Thanks for the update.  Note that only you can rule out a pebkac issue -- but your description does sound like it may be the case that you did not save or later deleted by accident.

If per-chance you have any time-machine backups (that is, I believe, apple's name for their backup system) you could try looking there to see if a PWG file appears in any of them.

In any case, I'm going to go ahead and close this as likely pebkac.
